### ISSUE TITLE
incompatibility with ruby2ruby

### ISSUE THREAD

**Issue by tario** [tario/partialruby#2]
Copied from  https://github.com/tario/shikashi/issues/11 (originally reported by delphaber)
"
I've noticed that recent version of ruby2ruby (2.0.1) breaks shikashi sandbox. No erros, but it returns always nil.

Resolved with this line added to my Gemfile

gem 'ruby2ruby', '~> 1.3'
"

**Comment by tario** [comment]
Fixed on 8624f1a30635a0b87d23532f0ffb3ad20b167a84 (released as version 0.2.1)

**Comment by delphaber** [comment]
Awesome! Thanks :+1:
